services:
  # Web Service - 100% GRATUIT
  - type: web
    name: croco-brasseur-website
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: croco_brasseur_db
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health

# Base de donnees MySQL GRATUITE - Railway ou PlanetScale
# Voir DEPLOYMENT_FREE.md pour les instructions
